# Generated by Django 4.1.4 on 2023-01-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpttcomment",
            name="old",
            field=models.BooleanField(default=False),
        ),
    ]
