# Generated by Django 4.1.4 on 2023-01-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_mpttcomment_old"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mpttcomment", options={"ordering": ["submit_date", "lft"]},
        ),
    ]
