# Generated by Django 4.1.4 on 2022-12-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("press", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
