# Generated by Django 4.1.4 on 2022-12-16 20:58

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("press", "0003_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=markdownx.models.MarkdownxField(
                default="# Edit here to create your first and only post!\n(you can edit it later if you want)"
            ),
        ),
    ]
