# Generated by Django 4.1.4 on 2022-12-19 16:25

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("press", "0005_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="pic",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default="default_pic.png",
                force_format=None,
                keep_meta=True,
                quality=-1,
                scale=True,
                size=[128, 128],
                upload_to="profile_pic",
            ),
        ),
    ]
