# Generated by Django 4.1.4 on 2023-01-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("press", "0007_alter_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="post", name="modified_at", field=models.DateField(null=True),
        ),
    ]
